### ISSUE TITLE
Confabulous + Systemic not working for jest version 27

### ISSUE THREAD

**Issue by Bounteous17** [guidesmiths/confabulous#11]
![Screenshot_20211104_132826](https://user-images.githubusercontent.com/16175933/140313462-1a6bee45-1149-41d9-94c3-9f9eef1c266b.png)
![Screenshot_20211104_132930](https://user-images.githubusercontent.com/16175933/140313548-9798439b-45e2-4e41-ad2d-a091e0d024c7.png)

**Comment by cressie176** [comment]
It doesn't look like jest plays nicely with [fs.watch](https://github.com/guidesmiths/confabulous/blob/master/lib/loaders/require.js#L46-L48) when you use --detectOpenHandles. I'm not sure there's anything confabulous can do about this. You could disable watching when running tests though.

**Comment by cressie176** [comment]
I'll take that back. The issue is that Confabulous doesn't include a shutdown operation, and consequently the file watcher is never closed. This will need to be added, then the systemic component updated with a stop function that calls it.

**Comment by cressie176** [comment]
`confabulous.close()` added in v2.1.0

This will cause the watchers to be removed and Jest will stop complaining.
