### ISSUE TITLE
Unexpected behaviour when merging deep levels

### ISSUE THREAD

**Issue by feliun** [guidesmiths/confabulous#2]
I've tried to use confabulous to merge different configurations for rabbitmq. In my test.json I'm including some queues binding, queues etc for test, and I don't want them to be mixed up with the defaults one.

What happens now is that confabulous is returning both the values for defaults.json + test.json, which makes testing impossible since queues configuration get mixed up (unless I move the config from defaults onto the rest of the environments to exclude test.json).

The culprit is [this line](https://github.com/guidesmiths/confabulous/blob/master/lib/merge.js#L5). Because we are using the `recursive` method, it is merging to the deepest level, which doesn't allow other config files to override files at a higher level.

Proof:

```
const merge = require('merge');
const defaultConfig = {
    subscriptions: {
        'this_one': 'should be overriden'
    }
};
const testConfig = {
    subscriptions: {
        'this_other_one': 'should be the only one'
    }
};
console.log(merge.apply(null, [true, defaultConfig, testConfig]));
// { subscriptions: { this_other_one: 'should be the only one' } }
```

VS

```
const merge = require('merge');
const defaultConfig = {
    subscriptions: {
        'this_one': 'should be overriden'
    }
};
const testConfig = {
    subscriptions: {
        'this_other_one': 'should be the only one'
    }
};
console.log(merge.recursive.apply(null, [true, defaultConfig, testConfig]));
/ * { subscriptions:
   { this_one: 'should be overriden',
     this_other_one: 'should be the only one' } }
*/
```

Also, setting the variable I want to remove to 'undefined' in the test file didn't do the trick. 

It's interesting, I'm assuming we don't want to override high level objects completely as that will force us to replicate the same config in other files (test etc). Is there any option in confabulous that help resolve this issue?

**Comment by cressie176** [comment]
Hi Felipe,

Recursively merging configuration in the specified order is the desired behaviour. If you want to exclude a configuration source in specific circumstances you can something like...

```
const c = new Confabulous()
if (APP_ENV !== 'test') c.add(config => loaders.require({ path: './conf/defaults.js' }))
c.add(config => loaders.require({ path: `./conf/${APP_ENV}.js` }))
c.end((err, config) => {
  // Your code goes here
})
```

However I'm curious as to why you need to do this. 

1. What problems are caused by having both subscriptions?
1. Why not override the default subscription with the test one by using the same name?

**Comment by feliun** [comment]
Thanks for the feedback @cressie176 . I just wanted to know what was the expected behaviour because I got a bit confused. Your solution excluding some loaders based on env is good. However I think it's simpler just to override the subscription, I just wanted to know what was expected/acceptable under the use of confabulous, what you said makes sense.

**Comment by cressie176** [comment]
Also I think if you override the default subscription with `null` rather than `undefined`, the end result will be null, however I'm not sure [rascal](https://github.com/guidesmiths/rascal) will like that.
