### ISSUE TITLE
support typescript

### ISSUE THREAD

**Issue by zuohuadong** [guidesmiths/confabulous#3]
support typescript

**Comment by cressie176** [comment]
Hi @zuohuadong,

Thanks for your suggestion. At this stage there's I have no interest in supporting typescript. It creates too much overhead. While I suspect typescript will be here to stay, when I've supported additional layers on other projects in the past, they've often fallen out of fashion, resulting in legacy. Sorry to disappoint.

**Comment by zuohuadong** [comment]
https://redmonk.com/sogrady/2019/07/18/language-rankings-6-19/

typescript is  No.10
